<a href="https://colab.research.google.com/github/Harisudharshan-2005/Hari_summer_internship/blob/main/Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)

In [ ]:
import pandas as pd
import numpy as pd
import requests
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

print('All Libraries improted successfully!')
print(f'pandas Installed ')

In [3]:
import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')
print("==== Warnings Ignored ====")
print("Pandas Installed :",pd.__version__)
print("Numpy Installed :",np.__version__)
print("Requests Installed :",requests.__version__)
print("==== Packages Installed Successfully ====")

==== Warnings Ignored ====
Pandas Installed : 2.2.2
Numpy Installed : 2.0.2
Requests Installed : 2.32.4
==== Packages Installed Successfully ====

In [4]:
data = pd.read_csv("/content/messy_sales_data.csv")

In [5]:
data.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [6]:
print("=== Data Quantity Analysis ===")
print("")
print("Number of Missing values")
print(data.isnull().sum())
print("")
print("Number of Duplicate Values")
print(data.duplicated().sum())
print("")
print("Data Types of the elements")
print(data.dtypes)

=== Data Quantity Analysis ===

Number of Missing values
order_id         0
customer_name    2
product          1
category         1
quantity         3
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Number of Duplicate Values
0

Data Types of the elements
order_id           int64
customer_name     object
product           object
category          object
quantity         float64
unit_price         int64
order_date        object
city              object
sales_rep         object
dtype: object

In [8]:
print("=== Unique category name ===")
print(data['category'].unique())
print("")
print("=== Sample Customer name ===")
print(data['customer_name'].dropna().unique()[:8])
print("")
print("=== Order Date analysis ===")
print(data['order_date'].unique()[:6])

=== Unique category name ===
['Electronics' 'Accessories' nan]

=== Sample Customer name ===
['Ramesh Kumar' 'Priya Nair' 'AMIT VERMA' 'Sunita Patel' 'kiran mehta'
 'Deepak Singh' 'Ananya Das' 'Vikram Iyer']

=== Order Date analysis ===
['2024-01-05' '2024-01-07' '2024-01-08' '2024-01-10' '07-01-2024'
 '2024-01-12']

In [9]:
print("Number of Missing values")
print(data['quantity'].isnull().sum())

Number of Missing values
3

In [10]:
df = data.copy()
df.head()

,order_id,customer_name,product,category,quantity,unit_price,order_date,city,sales_rep
0,1001,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma
1,1002,Priya Nair,NaN,Electronics,1.0,15000,2024-01-07,Delhi,Sunita Rao
2,1003,AMIT VERMA,Keyboard,Accessories,3.0,1200,2024-01-08,Bangalore,Anil Sharma
3,1004,Sunita Patel,Monitor,Electronics,NaN,22000,2024-01-10,Chennai,Ravi Kumar
4,1005,Ramesh Kumar,Laptop,Electronics,2.0,45000,2024-01-05,Mumbai,Anil Sharma

In [11]:
print("=== Finding the Total Missing Values in the copied Dataset ===")
print(df.isnull().sum().sum())

=== Finding the Total Missing Values in the copied Dataset ===
7

In [12]:
print(df['customer_name'].isnull().sum())

2

In [13]:
df['customer_name'].fillna('Unknown Customer' ,inplace = True)
print(df['customer_name'])

0         Ramesh Kumar
1           Priya Nair
2           AMIT VERMA
3         Sunita Patel
4         Ramesh Kumar
5          kiran mehta
6         Deepak Singh
7     Unknown Customer
8           Ananya Das
9          Vikram Iyer
10         Pooja Gupta
11          SURESH RAO
12         Meera Joshi
13          Arjun Nair
14         Tanvi Mehta
15         Kiran Mehta
16        Deepak Singh
17         Rohit Verma
18         Sneha Reddy
19       Gaurav Shukla
20        Nisha Kapoor
21         Ajay Tiwari
22          ANANYA DAS
23       Preeti Saxena
24           Amit Bose
25    Unknown Customer
26          Rekha Nair
27       Harish Pillai
28        Sanjay Dubey
29       Kavya Nambiar
Name: customer_name, dtype: object

In [17]:
# Fill numeric columns with mean
df['quantity'].fillna(df['quantity'].mean(), inplace=True)

# Fill categorical columns with mode
df['city'].fillna(df['city'].mode()[0], inplace=True)

print("\nAfter Fixing Missing Values:")
print(df.isnull().sum())

print("\nTotal Missing Values:", df.isnull().sum().sum())

After Fixing Missing Values:
order_id         0
customer_name    0
product          1
category         1
quantity         0
unit_price       0
order_date       0
city             0
sales_rep        0
dtype: int64

Total Missing Values: 2

In [22]:
print("before duplication :",len(df),"rows")
print("duplicate rows :",df.duplicated().sum())
print(df[df.duplicated(keep=False)])

before duplication : 30 rows
duplicate rows : 0
Empty DataFrame
Columns: [order_id, customer_name, product, category, quantity, unit_price, order_date, city, sales_rep]
Index: []

In [23]:
print("Missing values in 'product' column:", df['product'].isnull().sum())

Missing values in 'product' column: 1

In [24]:
print("=== Total Missing Values in Product ===")
print(df['product'].isnull().sum())
df['product'].fillna(df['product'].mode()[0],inplace = True)
df['product'].fillna(df['product'].mode()[0])

=== Total Missing Values in Product ===
1

0         Laptop
1         Laptop
2       Keyboard
3        Monitor
4         Laptop
5          Mouse
6     Headphones
7         Webcam
8         Laptop
9       Keyboard
10       Monitor
11       USB Hub
12        Laptop
13    Headphones
14        Webcam
15         Mouse
16      Keyboard
17       Monitor
18        Laptop
19       USB Hub
20    Headphones
21        Webcam
22        Laptop
23      Keyboard
24         Mouse
25    Headphones
26       Monitor
27        Laptop
28       USB Hub
29        Webcam
Name: product, dtype: object

In [25]:
print("=== Total Missing Values in Product ===")
print(df['product'].isnull().sum())

=== Total Missing Values in Product ===
0

In [26]:
print("Before Deduplication : ",len(df),"rows")
print("Duplicate Rows : ",df.duplicated().sum())
print(df[df.duplicated(keep = False)][['product']])
df.drop_duplicates(inplace = True)
print("After Deduplication : ",len(df),"rows")
print("Removed Rows : ",len(data) - len(df))

Before Deduplication :  30 rows
Duplicate Rows :  0
Empty DataFrame
Columns: [product]
Index: []
After Deduplication :  30 rows
Removed Rows :  0

In [27]:
print("=== Sample Dates Before parsing ===")
print(df['order_date'].head(8).tolist())

df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=False,
    errors='coerce'
)
nat_count = df['order_date'].isnull().sum()
print("Unparsable dates : ",nat_count)
df['year'] = df['order_date'].dt.year
df['month'] = df['order_date'].dt.month
df['month_name'] = df['order_date'].dt.strftime('%B')
print("=== sample dates after parsing ===")
print(df[['order_date','year','month','month_name']].head(8))

=== Sample Dates Before parsing ===
['2024-01-05', '2024-01-07', '2024-01-08', '2024-01-10', '2024-01-05', '07-01-2024', '2024-01-12', '2024-01-13']
Unparsable dates :  2
=== sample dates after parsing ===
  order_date    year  month month_name
0 2024-01-05  2024.0    1.0    January
1 2024-01-07  2024.0    1.0    January
2 2024-01-08  2024.0    1.0    January
3 2024-01-10  2024.0    1.0    January
4 2024-01-05  2024.0    1.0    January
5        NaT     NaN    NaN        NaN
6 2024-01-12  2024.0    1.0    January
7 2024-01-13  2024.0    1.0    January

In [28]:
df['order_date'] = pd.to_datetime(df['order_date'], format='mixed', dayfirst=True, errors='coerce')
df['day'] = df['order_date'].dt.day
df['month'] = df['order_date'].dt.month
df['year'] = df['order_date'].dt.year
df['month_name'] = df['order_date'].dt.strftime('%B')

print("DataFrame with 'day', 'month', 'year', and 'month_name' columns:")
print(df[['order_date', 'day', 'month', 'year', 'month_name']].head())

DataFrame with 'day', 'month', 'year', and 'month_name' columns:
  order_date   day  month    year month_name
0 2024-01-05   5.0    1.0  2024.0    January
1 2024-01-07   7.0    1.0  2024.0    January
2 2024-01-08   8.0    1.0  2024.0    January
3 2024-01-10  10.0    1.0  2024.0    January
4 2024-01-05   5.0    1.0  2024.0    January